openapi: 3.0.0
info:
  title: envd
  version: 0.1.0
  description: API for managing files' content and controlling envd

tags:
  - name: files

paths:
  /host/sync:
    post:
      summary: Ensure the time and metadata is synced with the host
      responses:
        204:
          description: The time and metadata is synced with the host
        500:
          $ref: "#/components/responses/InternalServerError"

  /files/{path}:
    get:
      summary: Download a file
      tags: [files]
      parameters:
        - $ref: "#/components/parameters/FilePath"
      responses:
        200:
          $ref: "#/components/responses/DownloadSuccess"
        400:
          $ref: "#/components/responses/DirectoryPathError"
        500:
          $ref: "#/components/responses/InternalServerError"
    put:
      summary: Upload a file and ensure the parent directories exist. If the file exists, it will be overwritten.
      tags: [files]
      parameters:
        - $ref: "#/components/parameters/FilePath"
        - $ref: "#/components/parameters/User"
      requestBody:
        $ref: "#/components/requestBodies/File"
      responses:
        200:
          $ref: "#/components/responses/ExistingFileUploadSuccess"
        201:
          $ref: "#/components/responses/NewFileUploadSuccess"
        400:
          $ref: "#/components/responses/DirectoryPathError"
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  parameters:
    FilePath:
      name: path
      in: path
      required: true
      allowEmptyValue: true
      description: Absolute path to the file, URL encoded.
      schema:
        type: string
    User:
      name: user
      in: query
      required: true
      description: User owning the file
      schema:
        type: string

  requestBodies:
    File:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary

  responses:
    ExistingFileUploadSuccess:
      description: The file was updated successfully.
      headers:
        Cache-Control:
          schema:
            type: string
            example: "no-cache, no-store"
    NewFileUploadSuccess:
      description: The file was created successfully.
      headers:
        Cache-Control:
          schema:
            type: string
            example: "no-cache, no-store"
        Location:
          description: The URL of the uploaded file
          schema:
            type: string
            format: path
    DownloadSuccess:
      description: Entire file downloaded successfully.
      headers:
        Cache-Control:
          schema:
            type: string
            example: "no-cache, no-store"
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
            description: The file content
    DirectoryPathError:
      description: Bad Request - The specified path is a directory.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: integer
          description: Error code
