version: "3.8"

services:
  api:
    image: e2b/api:latest
    build:
      context: ./api-service
    environment:
      - PORT=49155
      - SUPABASE_URL=http://supabase_kong_workspace:8000
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - 49155
    external_links:
      - supabase_kong_workspace
      - supabase_db_workspace
    networks:
      - supabase-local-net

  app-dev:
    image: e2b/app-dev:latest
    build:
      context: ./
      args:
        NEXT_PUBLIC_SIGN_IN_EMAIL: admin@admin.com
        NEXT_PUBLIC_SIGN_IN_PASSWORD: admin@admin.com
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    external_links:
      - supabase_kong_workspace
      - supabase_db_workspace
    environment:
      - NODE_ENV=development
      - SUPABASE_URL=http://supabase_kong_workspace:8000
      - API_URL=http://api:49155
      - SUPABASE_POSTGRES_URL=postgresql://postgres:postgres@supabase_db_workspace:5432/postgres
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - 3000:3000
    networks:
      - supabase-local-net

networks:
  supabase-local-net:
    # This name identified the network with supabase containers started with `supabase start`.
    name: supabase_network_workspace
    external: true