import {
  Home,
  // BarChart,
  // BookOpen,
  // Braces,
  // ChevronRightSquare,
  // Cog,
  // Cpu,
  // DollarSign,
  // File,
  // FileDown,
  // FileUp,
  // Folder,
  // FolderTree,
  // Hammer,
  // HardDrive,
  // KeyRound,
  // Link,
  // PencilRuler,
  // PlaySquare,
  // RefreshCw,
  // Settings,
  // ShieldQuestion,
  // Terminal,
  // TerminalSquare,
  // Timer,
  // Variable,
  // Wrench,
} from 'lucide-react'

// import logoNode from '@/images/logos/node.svg'
// import logoPython from '@/images/logos/python.svg'
// import Image from 'next/image'

// @ts-ignore; generated by prebuild.ts




// Three parts
//
// 1. Documentation
//    - Concepts - "filesystem", "what is sandbox", ...
//    - How to's (guides?) - simple examples of things like "how to run AI-generated code" or "how to install custom packages" or "how to add language runtime" or "how to upload files" or "how to change current working directory" or "how to add another user" or "how to set up environment variables"
//      - This could be additionally split into parts like "Customization", "Running AI-generated code"
//    - Integrations
// 2. Cookbook?
// 3. API Reference
//    - API spec
//    - Python SDK
//    - JS SDK
//
//
//
//
// Note:
// - We need some kind of "first steps" that's super simple
// - Having something like
// - Maybe have following separate pages:
//   - Documentation
//   - Reference
//   - Integrations
//   - Cookbook
//


export interface NavLink {
  title: string
  href: string
  icon?: React.ReactNode
}

export interface NavSubgroup {
  title: string
  links: NavLink[]
}

export interface NavGroup {
  title?: string
  items: Array<NavLink | NavSubgroup>
  // links?: NavLink[]
  // subgroups?: NavSubgroup[]
}


// export interface NavGroupWithLinks {
//   title?: string
//   links: NavLink[]
//   subgroups?: never // This ensures that subgroups is not present when links is used
// }

// export interface NavGroupWithSubgroups {
//   title?: string
//   links?: never // This ensures that links is not present when subgroups is used
//   subgroups: NavSubgroup[]
// }

// export type NavGroup = NavGroupWithLinks | NavGroupWithSubgroups

export const routes: NavGroup[] = [
  {
    items: [
      {
        title: 'Home',
        href: '/docs',
        icon: <Home size={16} />,
      },
    ],
  },
  {
    title: 'Quickstart',
    items: [
      {
        title: 'Start E2B Sandbox',
        href: '/docs/hello-world/js',
      },
    ]
  },
  {
    title: 'Guides', // How to's
    items: [
      {
        title: 'Execute AI-generated code',
        href: '/docs/a',
      },
      {
        title: 'Install custom packages',
        href: '/docs/b',
      },
      {
        title: 'Set environment variables',
        href: '/docs/c',
      },
      {
        title: 'Upload & download files',
        href: '/docs/d',
      },
      {
        title: 'Customize CPU and RAM',
        href: '/docs/e',
      },
      {
        title: 'Set working directory',
        href: '/docs/f',
      },
      {
        title: 'Link specific sandbox with user',
        href: '/docs/g',
      }
    ]
  },
  {
    title: 'AI Code Execution',
    items: [
      {
        title: 'Data analysis',
        links: [
          {
            title: 'Overview',
            href: '/docs/hello-world/py',
          },
          {
            title: 'Data visualization',
            href: '/docs/code-execution/overview',
          },
          {
            title: 'Interactive charts',
            href: '/docs/code-execution/overview',
          },
        ]
      },
      {
        title: 'Python',
        href: '/docs/code-execution/python',
      },
      {
        title: 'JavaScript',
        href: '/docs/code-execution/python',
      },
      {
        title: 'TypeScript',
        href: '/docs/code-execution/python',
      },
      {
        title: 'Custom language',
        href: '/docs/code-execution/python',
      },
    ],
  },
  {
    title: 'Sandbox',
    items: [
      {
        title: 'Lifecycle',
        href: '/docs/sandbox/lifecycle',
      },
      {
        title: 'Metadata',
        href: '/docs/sandbox/filesystem',
      },
      {
        title: 'Customization',
        href: '/docs/sandbox/customization',
      }
    ],
  },
  {
    title: 'Filesystem',
    items: [
      {
        title: 'Overview',
        href: '/docs/filesystem/overview',
      },
    ]
  },
  {
    title: 'Commands',
    items: [
      {
        title: 'Overview',
        href: '/docs/process/overview',
      },

    ]
  },
  {
    // Maybe move integrations to a separate page?
    title: 'Integrations',
    items: [
      {
        title: 'OpenAI',
        href: '/docs/integrations/openai',
      },
      {
        title: 'Vercel AI SDK',
        href: '/docs/integrations/ai-sdk',
      },
      {
        title: 'Langchain',
        href: '/docs/integrations/ai-sdk',
      },
    ]
  },
  // ...apiRefRoutes,
]

