# coding: utf-8

"""
    playground

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import playground_client
from playground_client.models.open_port import OpenPort  # noqa: E501
from playground_client.rest import ApiException

class TestOpenPort(unittest.TestCase):
    """OpenPort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OpenPort
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenPort`
        """
        model = playground_client.models.open_port.OpenPort()  # noqa: E501
        if include_optional :
            return OpenPort(
                state = '', 
                ip = '', 
                port = 1.337
            )
        else :
            return OpenPort(
                state = '',
                ip = '',
                port = 1.337,
        )
        """

    def testOpenPort(self):
        """Test OpenPort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
