// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package api

// Defines values for EnvironmentStatus.
const (
	EnvironmentStatusBuilding EnvironmentStatus = "Building"

	EnvironmentStatusDone EnvironmentStatus = "Done"

	EnvironmentStatusFailed EnvironmentStatus = "Failed"
)

// Defines values for EnvironmentStatusStatus.
const (
	EnvironmentStatusStatusBuilding EnvironmentStatusStatus = "Building"

	EnvironmentStatusStatusDone EnvironmentStatusStatus = "Done"

	EnvironmentStatusStatusFailed EnvironmentStatusStatus = "Failed"
)

// Defines values for NewEnvironmentRuntime.
const (
	NewEnvironmentRuntimeNodejs NewEnvironmentRuntime = "Nodejs"
)

// Environment defines model for Environment.
type Environment struct {
	// Embedded struct due to allOf(#/components/schemas/NewEnvironment)
	NewEnvironment `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Id     string            `json:"id"`
	Status EnvironmentStatus `json:"status"`
}

// EnvironmentStatus defines model for Environment.Status.
type EnvironmentStatus string

// EnvironmentStatusStatus defines model for EnvironmentStatus.Status.
type EnvironmentStatusStatus string

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error
	Message string `json:"message"`
}

// NewEnvironment defines model for NewEnvironment.
type NewEnvironment struct {
	CodeSnippetID string                `json:"codeSnippetID"`
	Deps          []string              `json:"deps"`
	Runtime       NewEnvironmentRuntime `json:"runtime"`
}

// NewEnvironmentRuntime defines model for NewEnvironment.Runtime.
type NewEnvironmentRuntime string

// NewSession defines model for NewSession.
type NewSession struct {
	// Identifier of a code snippet which which is the environment associated
	CodeSnippetID string `json:"codeSnippetID"`
}

// Session defines model for Session.
type Session struct {
	// Identifier of the client
	ClientID string `json:"clientID"`

	// Identifier of the session
	SessionID string `json:"sessionID"`
}

// PostEnvsCodeSnippetIDStatusJSONBody defines parameters for PostEnvsCodeSnippetIDStatus.
type PostEnvsCodeSnippetIDStatusJSONBody EnvironmentStatus

// PostSessionsJSONBody defines parameters for PostSessions.
type PostSessionsJSONBody NewSession

// PostEnvsCodeSnippetIDStatusJSONRequestBody defines body for PostEnvsCodeSnippetIDStatus for application/json ContentType.
type PostEnvsCodeSnippetIDStatusJSONRequestBody PostEnvsCodeSnippetIDStatusJSONBody

// PostSessionsJSONRequestBody defines body for PostSessions for application/json ContentType.
type PostSessionsJSONRequestBody PostSessionsJSONBody
