// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file envd/filesystem/v1/filesystem.proto (package envd.filesystem.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListRequest, ListResponse, RemoveRequest, RemoveResponse, StatRequest, StatResponse, WatchRequest, WatchResponse } from "./filesystem_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service envd.filesystem.v1.FilesystemService
 */
export const FilesystemService = {
  typeName: "envd.filesystem.v1.FilesystemService",
  methods: {
    /**
     * @generated from rpc envd.filesystem.v1.FilesystemService.Stat
     */
    stat: {
      name: "Stat",
      I: StatRequest,
      O: StatResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc envd.filesystem.v1.FilesystemService.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc envd.filesystem.v1.FilesystemService.Watch
     */
    watch: {
      name: "Watch",
      I: WatchRequest,
      O: WatchResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc envd.filesystem.v1.FilesystemService.Remove
     */
    remove: {
      name: "Remove",
      I: RemoveRequest,
      O: RemoveResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

