// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package handlers

// Defines values for EnvironmentRuntime.
const (
	EnvironmentRuntimeNodejs EnvironmentRuntime = "nodejs"
)

// AnyValue defines model for AnyValue.
type AnyValue interface{}

// Environment defines model for Environment.
type Environment struct {
	// Identifier of a code snippet which which is the environment associated
	CodeSnippetId string             `json:"code_snippet_id"`
	Deps          []string           `json:"deps"`
	Runtime       EnvironmentRuntime `json:"runtime"`
}

// EnvironmentRuntime defines model for Environment.Runtime.
type EnvironmentRuntime string

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error
	Message string `json:"message"`
}

// Session defines model for Session.
type Session struct {
	// Identifier of the client
	ClientId string `json:"client_id"`

	// Identifier of the session
	SessionId string `json:"session_id"`
}

// SessionForm defines model for SessionForm.
type SessionForm struct {
	// Identifier of a code snippet which which is the environment associated
	CodeSnippetId string `json:"code_snippet_id"`
}

// PostSessionsJSONBody defines parameters for PostSessions.
type PostSessionsJSONBody SessionForm

// PostSessionsJSONRequestBody defines body for PostSessions for application/json ContentType.
type PostSessionsJSONRequestBody PostSessionsJSONBody
