-- Create "envs" table
CREATE TABLE "envs" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "team_id" uuid NOT NULL, "dockerfile" character varying NOT NULL, "status" character varying NOT NULL, "public" boolean NOT NULL, "build_id" uuid NOT NULL, PRIMARY KEY ("id"));
-- Create "team_api_keys" table
CREATE TABLE "team_api_keys" ("api_key" character varying NOT NULL, "created_at" timestamptz NOT NULL, "team_id" uuid NOT NULL, PRIMARY KEY ("api_key"));
-- Create "teams" table
CREATE TABLE "teams" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "is_default" boolean NOT NULL, "name" character varying NOT NULL, "is_blocked" boolean NOT NULL, "env_team" character varying NULL, "team_api_key_team" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "teams_envs_team" FOREIGN KEY ("env_team") REFERENCES "envs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "teams_team_api_keys_team" FOREIGN KEY ("team_api_key_team") REFERENCES "team_api_keys" ("api_key") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "access_tokens" table
CREATE TABLE "access_tokens" ("access_token" character varying NOT NULL, "user_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("access_token"));
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL, "email" character varying NOT NULL, "access_token_users" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "users_access_tokens_users" FOREIGN KEY ("access_token_users") REFERENCES "access_tokens" ("access_token") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "users_teams" table
CREATE TABLE "users_teams" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" uuid NOT NULL, "team_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "users_teams_teams_teams" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "users_teams_users_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "usersteams_team_id_user_id" to table: "users_teams"
CREATE UNIQUE INDEX "usersteams_team_id_user_id" ON "users_teams" ("team_id", "user_id");
