# content of pytest.ini
[pytest]
markers =
    skip_debug: skip test if E2B_DEBUG is set.
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session

addopts = "--import-mode=importlib" "--numprocesses=2"
