# This is a config for E2B sandbox template.
# You can use 'template_id' (0srgkoat7xpo3x9y1jf1) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='0srgkoat7xpo3x9y1jf1')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: '0srgkoat7xpo3x9y1jf1' })

dockerfile = "Dockerfile"
template_id = "0srgkoat7xpo3x9y1jf1"
