# This is a config for E2B sandbox template.
# You can use 'template_id' (75pwqumpm5czu79t7556) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='75pwqumpm5czu79t7556')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: '75pwqumpm5czu79t7556' })

dockerfile = "Dockerfile"
template_id = "75pwqumpm5czu79t7556"
