# This is a config for E2B sandbox template.
# You can use 'template_id' (kimiw4qi0y7g5dvzjg7t) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='kimiw4qi0y7g5dvzjg7t')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'kimiw4qi0y7g5dvzjg7t' })

dockerfile = "Dockerfile"
template_id = "kimiw4qi0y7g5dvzjg7t"
