# coding: utf-8

"""
    Devbook

    Devbook API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import client
from client.models.envs_get200_response_inner import (
    EnvsGet200ResponseInner,
)  # noqa: E501
from client.rest import ApiException


class TestEnvsGet200ResponseInner(unittest.TestCase):
    """EnvsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EnvsGet200ResponseInner
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EnvsGet200ResponseInner`
        """
        model = client.models.envs_get200_response_inner.EnvsGet200ResponseInner()  # noqa: E501
        if include_optional :
            return EnvsGet200ResponseInner(
                id = '', 
                template = '', 
                title = ''
            )
        else :
            return EnvsGet200ResponseInner(
                id = '',
        )
        """

    def testEnvsGet200ResponseInner(self):
        """Test EnvsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
