# This is a config for E2B sandbox template.
# You can use 'template_id' (4un52r18xomwxmilmzfa) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='4un52r18xomwxmilmzfa')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: '4un52r18xomwxmilmzfa' })

dockerfile = "Dockerfile"
template_id = "4un52r18xomwxmilmzfa"
