/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/files/{path}": {
    /** Download a file */
    get: {
      parameters: {
        query: {
          username: components["parameters"]["User"];
        };
        path: {
          path: components["parameters"]["FilePath"];
        };
      };
      responses: {
        200: components["responses"]["DownloadSuccess"];
        400: components["responses"]["BadRequest"];
        403: components["responses"]["DirectoryPathError"];
        404: components["responses"]["FileNotFound"];
        500: components["responses"]["InternalServerError"];
      };
    };
    /** Upload a file and ensure the parent directories exist. If the file exists, it will be overwritten. */
    post: {
      parameters: {
        query: {
          username: components["parameters"]["User"];
        };
        path: {
          path: components["parameters"]["FilePath"];
        };
      };
      requestBody: components["requestBodies"]["File"];
      responses: {
        200: components["responses"]["ExistingFileUploadSuccess"];
        201: components["responses"]["NewFileUploadSuccess"];
        400: components["responses"]["BadRequest"];
        403: components["responses"]["DirectoryPathError"];
        500: components["responses"]["InternalServerError"];
        507: components["responses"]["NotEnoughDiskSpace"];
      };
    };
  };
  "/sync": {
    /** Ensure the time and metadata is synced with the host */
    post: {
      responses: {
        /** @description The time and metadata is synced with the host */
        204: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Error: {
      /** @description Error code */
      code: number;
      /** @description Error message */
      message: string;
    };
  };
  responses: {
    /** @description Bad request */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Directory path error */
    DirectoryPathError: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Entire file downloaded successfully. */
    DownloadSuccess: {
      content: {
        "application/octet-stream": string;
      };
    };
    /** @description The file was updated successfully. */
    ExistingFileUploadSuccess: {
      content: never;
    };
    /** @description File not found */
    FileNotFound: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Internal server error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The file was created successfully. */
    NewFileUploadSuccess: {
      content: never;
    };
    /** @description Not enough disk space */
    NotEnoughDiskSpace: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description Path to the file, URL encoded. Can be relative to user's home directory. */
    FilePath: string;
    /** @description User used for setting the owner, or resolving relative paths. */
    User: string;
  };
  requestBodies: {
    File: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file?: string;
        };
      };
    };
  };
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
