# This is a config for E2B sandbox template.
# You can use 'template_id' (3pbjtwbp9liugfe9hijp) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='3pbjtwbp9liugfe9hijp')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: '3pbjtwbp9liugfe9hijp' })

dockerfile = "Dockerfile"
template_id = "3pbjtwbp9liugfe9hijp"
