name: Test JS SDK

on:
  push:
    paths:
      - packages/js-sdk/**/*
      - .github/workflows/js_tests.yml

permissions:
  contents: read

jobs:
  publish:
    defaults:
      run:
        working-directory: ./packages/js-sdk
    name: Build and test SDK
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test build
        run: npm run build

      - name: Run tests
        run: npm run test
        env:
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}
