name: Linting

on:
  pull_request:
    branches: [main]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check packages/python-sdk/

  lint-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Biome
        run: npm install --save-dev @biomejs/biome
      - name: Run Biome
        run: npx @biomejs/biome ci packages/js-sdk/
