name: Release tooling tests

on:
  pull_request:
    paths:
      - '.github/scripts/**'
      - '.github/workflows/release*.yml'
      - '.github/workflows/publish_packages.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: wistia/parse-tool-versions@32f568a4ffd4bfa7720ebf93f171597d1ebc979a # v2.1.1
        with:
          filename: '.tool-versions'
          uppercase: 'true'
          prefix: 'tool_version_'
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        with:
          version: '${{ env.TOOL_VERSION_PNPM }}'
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: '${{ env.TOOL_VERSION_NODEJS }}'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test:release
